### ISSUE TITLE
B3 profile isn't accessible in v.2.0b.2

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#7]
When clicking on the Admin I should be able to change my profile and the B3 profile. Only the my profile can be changed. The B3 profiles isn't accessible.

**Comment by MichaelHillcox** [comment]
@wassie Where you able to edit your b3 profile before hand in the older versions of echelon?

**Comment by wassie** [comment]
the first time when you install Echelon, you can setup B3 credentials. After that you can change things in screen attached. 

![2017-02-26_21-37-25](https://cloud.githubusercontent.com/assets/17354054/23343438/d65a2ab8-fc6b-11e6-908f-c21804bf1f00.jpg)

**Comment by MichaelHillcox** [comment]
This should be fixed with #6 Could you confirm?

**Comment by wassie** [comment]
The B3 profile still isn't accessible. Could it be that you only can use this option when having multiple B3 accounts, or profiles?

**Comment by MichaelHillcox** [comment]
I'm still very lost on what this is meant to be. Could you take a screenshot of the old echelon to show me what's no longer accessable

**Comment by wassie** [comment]
I see that I have created some confusion.... sorry for that.
What I mean is that in the new version of Echelon, you have in the upper right corner a menu item with the username in it. If you click on that menu item, you see a dropdown menu with profile and games. Under games you have the option 'B3 profiles'. That option show a small icon (red circle with a line) and the option isn't clickable, while the above option 'My profile' is clickable. The thing is that the old Echelon doesn't has that function, so its in this version.

**Comment by MichaelHillcox** [comment]
No, this feature hasn't yet been added. I need to make it not clickable :P

**Comment by wassie** [comment]
I see, so no bug and can be closed then :)
